(() => {
  const query = new URLSearchParams(location.search);
  const token = query.get('token') || sessionStorage.getItem('espDroneToken') || '';
  if (token) { sessionStorage.setItem('espDroneToken', token); query.delete('token'); history.replaceState(null, '', location.pathname + (query.toString() ? '?' + query : '')); }
  const headers = {'Content-Type': 'application/json', 'X-Access-Token': token};
  const defaults = {host:'192.168.1.19',port:4210,mode:2,deadzone:.2,rollTrim:0,pitchTrim:0,maxRollPitch:4,maxYaw:30,maxThrust:90,minThrust:25,xmode:false,fullThrust:false,joystickSize:100,showConsole:true};
  const settings = Object.assign({}, defaults, JSON.parse(localStorage.getItem('espDroneSettings') || '{}'));
  const stick = {left:{x:0,y:0,pointer:null},right:{x:0,y:0,pointer:null},locked:false};
  const $ = selector => document.querySelector(selector);
  const ui = {connect:$('#connectButton'),link:$('#linkQuality'),status:$('#uavStatus'),console:$('#console'),roll:$('#roll'),pitch:$('#pitch'),yaw:$('#yaw'),thrust:$('#thrust'),toast:$('#toast')};
  let pump = null, bridgeState = null;
  const api = body => fetch('/api/control', {method:'POST',headers,body:JSON.stringify(body)}).then(r => r.ok ? r.json() : r.json().then(x => Promise.reject(Error(x.error))));
  const tell = text => { ui.toast.textContent=text; ui.toast.classList.add('show'); setTimeout(() => ui.toast.classList.remove('show'), 2200); };
  const saveSettings = () => localStorage.setItem('espDroneSettings', JSON.stringify(settings));
  function mappedControl() {
    let rollAxis, pitchAxis, yawAxis, thrustAxis;
    if (settings.mode === 1) { rollAxis=stick.right.x; pitchAxis=stick.left.y; yawAxis=stick.left.x; thrustAxis=stick.right.y; }
    else if (settings.mode === 2) { rollAxis=stick.right.x; pitchAxis=stick.right.y; yawAxis=stick.left.x; thrustAxis=stick.left.y; }
    else if (settings.mode === 3) { rollAxis=stick.left.x; pitchAxis=stick.left.y; yawAxis=stick.right.x; thrustAxis=stick.right.y; }
    else { rollAxis=stick.left.x; pitchAxis=stick.right.y; yawAxis=stick.right.x; thrustAxis=stick.left.y; }
    const dz = n => Math.abs(n) <= settings.deadzone ? 0 : n;
    const throttle = settings.fullThrust ? Math.max(0, (thrustAxis + 1) / 2) : thrustAxis;
    return {roll:-(dz(rollAxis) * settings.maxRollPitch + settings.rollTrim), pitch:-(dz(pitchAxis) * settings.maxRollPitch + settings.pitchTrim), yaw:dz(yawAxis) * settings.maxYaw, throttle};
  }
  function paint() { for (const side of ['left','right']) $('#'+side+'Joystick').style.setProperty('--stick-x', (stick[side].x*75)+'%'), $('#'+side+'Joystick').style.setProperty('--stick-y', (-stick[side].y*75)+'%'); const c=mappedControl(), t=c.throttle>settings.deadzone ? settings.minThrust+c.throttle*(settings.maxThrust-settings.minThrust) : 0; ui.roll.value=c.roll.toFixed(0);ui.pitch.value=c.pitch.toFixed(0);ui.yaw.value=c.yaw.toFixed(0);ui.thrust.value=t.toFixed(0)+'%'; }
  function emit() { paint(); if (bridgeState && bridgeState.connected) api({action:'setpoint',...mappedControl()}).catch(()=>{}); }
  function isActive() { return stick.left.pointer !== null || stick.right.pointer !== null; }
  function startPump() { if (!pump) pump=setInterval(emit,100); }
  function stopPump() { if (!isActive() && pump) { clearInterval(pump); pump=null; if (bridgeState && bridgeState.connected) api({action:'setpoint',roll:0,pitch:0,yaw:0,throttle:0}).catch(()=>{}); } }
  function updateStick(side, event) { const area=event.currentTarget, rect=area.getBoundingClientRect(), radius=Math.min(rect.width,rect.height)*.30; let x=(event.clientX-(rect.left+rect.width/2))/radius, y=((rect.top+rect.height/2)-event.clientY)/radius; if (side==='left' && stick.locked) x=0; const length=Math.hypot(x,y); if(length>1){x/=length;y/=length;} if ((settings.mode===2 && side==='left') || (settings.mode===3 && side==='right')) { if(Math.abs(x)>Math.abs(y)) y=0; else x=0; } stick[side].x=x; stick[side].y=y; emit(); }
  function bindJoystick(side) { const area=$('#'+side+'Joystick'); area.addEventListener('pointerdown',event=>{event.preventDefault();stick[side].pointer=event.pointerId;area.setPointerCapture(event.pointerId);updateStick(side,event);startPump();}); area.addEventListener('pointermove',event=>{if(stick[side].pointer===event.pointerId)updateStick(side,event);}); for(const name of ['pointerup','pointercancel']) area.addEventListener(name,event=>{if(stick[side].pointer!==event.pointerId)return;stick[side].x=stick[side].y=0;stick[side].pointer=null;paint();if(isActive())emit();stopPump();}); }
  function lineValue(lines, expression) { const match=(lines.join('\n')).match(expression); return match ? match[1] : '?'; }
  function renderState(state) { bridgeState=state; settings.host=state.host;settings.port=state.port; const online=state.connected && state.telemetryAge !== null && state.telemetryAge < 3, lines=state.lines||[], arm=/ARM=1/.test(lines.join('\n')), altitude=lineValue(lines,/ALTm=([-\d.]+)/), mode=lineValue(lines,/MODE=(\d+)/), target=state.altitudeTarget === null ? '?' : state.altitudeTarget.toFixed(2); ui.link.textContent=state.connected?'UDP':'N/A';ui.connect.classList.toggle('connected',state.connected);ui.status.textContent=`Thiết bị: ${online?'SẴN SÀNG':'CHƯA SẴN SÀNG'}\nKết nối: ${state.connected?'Đã kết nối UDP tới '+state.host+':'+state.port:'Chưa kết nối'}\nARM: ${arm?'Đã bật':'Chưa bật'}\nĐộ cao: ${altitude} m | Mục tiêu: ${target} m\nChế độ cao: ${mode==='2'?'Giữ độ cao':mode==='3'?'Đang cất cánh':mode==='4'?'Đang hạ cánh':mode==='0'?'Tắt':'Chưa rõ'}`;ui.status.style.color=online?'#087f23':'#b00020';ui.console.textContent=lines.length?lines.join('\n'):'Đang chờ telemetry...';ui.console.scrollTop=ui.console.scrollHeight; }
  function refresh() { fetch('/api/state',{headers}).then(r=>r.ok?r.json():Promise.reject()).then(renderState).catch(()=>{ui.link.textContent='N/A';ui.status.textContent='Thiết bị: CHƯA SẴN SÀNG\nKết nối: Không liên lạc được gateway';}); }
  function toggleConnection() { if (bridgeState && bridgeState.connected) api({action:'disconnect'}).then(x=>{renderState(x.state);tell('Đã ngắt kết nối UDP');}).catch(e=>tell(e.message)); else api({action:'connect',host:settings.host,port:Number(settings.port)}).then(x=>{renderState(x.state);tell('Đang kết nối UDP...');}).catch(e=>tell(e.message)); }
  function field(label,key,type='number',hint='') { const value=type==='checkbox'?(settings[key]?'checked':''):settings[key]; return `<div class="field"><label>${type==='checkbox'?`<input type="checkbox" name="${key}" ${value}>`:''}${label}</label>${type==='checkbox'?'':`<input name="${key}" type="${type}" value="${value}" step="any">`}<small>${hint}</small></div>`; }
  const sections={connection:{title:'Kết nối Wi-Fi ESP32',html:()=>field('Địa chỉ IP ESP32','host','text','IP của ESP32 trong mạng Wi-Fi dùng chung')+field('Cổng UDP ESP32','port','number','Cổng nhận lệnh UDP của firmware ESP32')},flight:{title:'Cài đặt điều khiển bay',html:()=>`<div class="field"><label>Chế độ cần điều khiển</label><select name="mode">${[1,2,3,4].map(n=>`<option value="${n}" ${settings.mode===n?'selected':''}>Mode ${n}</option>`).join('')}</select><small>Mapping trục giống Controls.java</small></div>`+field('Vùng chết joystick','deadzone','number')+field('Bù lệch Roll','rollTrim','number')+field('Bù lệch Pitch','pitchTrim','number')+field('Góc Roll/Pitch tối đa','maxRollPitch','number')+field('Tốc độ Yaw tối đa','maxYaw','number')+field('Ga tối đa (%)','maxThrust','number')+field('Ga tối thiểu (%)','minThrust','number')+field('Chế độ khung X','xmode','checkbox','Đúng với tùy chọn Android; firmware quyết định việc áp dụng.')},controller:{title:'Cài đặt bộ điều khiển',html:()=>field('Dùng toàn hành trình cần độ cao','fullThrust','checkbox','Tương ứng Use full travel for thrust')+field('Kích thước joystick (%)','joystickSize','number','10–100; áp dụng ngay lên hai joystick web')},app:{title:'Cài đặt ứng dụng',html:()=>field('Hiện log kỹ thuật','showConsole','checkbox','Hiện hoặc ẩn console telemetry giống app Android')}};
  function openSection(name) { const section=sections[name];$('#preferenceList').classList.add('hidden');$('#settingsForm').classList.remove('hidden');$('#settingsTitle').textContent=section.title;$('#settingsFields').innerHTML=section.html();$('#settingsForm').dataset.section=name; }
  function closeSection() { $('#settingsForm').classList.add('hidden');$('#preferenceList').classList.remove('hidden'); }
  $('#settingsButton').onclick=()=>{$('#mainScreen').classList.add('hidden');$('#preferencesScreen').classList.remove('hidden');};$('#backButton').onclick=()=>{$('#preferencesScreen').classList.add('hidden');$('#mainScreen').classList.remove('hidden');closeSection();};document.querySelectorAll('[data-section]').forEach(button=>button.onclick=()=>openSection(button.dataset.section));$('#cancelSettings').onclick=closeSection;$('#aboutButton').onclick=()=>$('#aboutDialog').showModal();$('#aboutDialog button').onclick=()=>$('#aboutDialog').close();$('#settingsForm').onsubmit=event=>{event.preventDefault();const data=new FormData(event.currentTarget),section=event.currentTarget.dataset.section;for(const [key,value] of data.entries())settings[key]=['host'].includes(key)?value:Number(value);for(const key of ['xmode','fullThrust','showConsole'])settings[key]=data.get(key)==='on';settings.mode=Number(settings.mode);saveSettings();const size=Math.max(10,Math.min(100,Number(settings.joystickSize)||100));document.documentElement.style.setProperty('--joy-size',size/100);ui.console.classList.toggle('hidden',!settings.showConsole);if(section==='connection')api({action:'connect',host:settings.host,port:Number(settings.port)}).then(x=>renderState(x.state)).catch(e=>tell(e.message));closeSection();tell('Đã lưu cài đặt');paint();};
  $('#connectButton').onclick=toggleConnection;$('#leftHorizontalLock').onclick=event=>{stick.locked=!stick.locked;event.currentTarget.classList.toggle('locked',stick.locked);if(stick.locked){stick.left.x=0;emit();}};document.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>{const action=button.dataset.action;if(action==='arm'&&!confirm('Động cơ sẽ được cho phép hoạt động. Tiếp tục?'))return;if(['kill','takeoff','land'].includes(action)&&!confirm('Xác nhận lệnh '+action.toUpperCase()+'?'))return;api({action}).catch(e=>tell(e.message));});window.addEventListener('blur',()=>{for(const side of ['left','right']){stick[side].x=stick[side].y=0;stick[side].pointer=null;}paint();stopPump();});bindJoystick('left');bindJoystick('right');ui.console.classList.toggle('hidden',!settings.showConsole);paint();refresh();setInterval(refresh,700);
})();
